# Generated by Django 4.0.3 on 2023-06-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
