# Generated by Django 4.0.3 on 2023-06-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherui', '0002_remove_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
