# Generated by Django 4.0.3 on 2023-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherui', '0006_alter_teacher_num_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='num_classes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
