# Generated by Django 4.0.3 on 2023-06-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherui', '0002_student_srr'),
        ('teacherui', '0007_alter_teacher_num_classes'),
    ]

    operations = [
    ]
