# Generated by Django 4.0.3 on 2023-06-25 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherui', '0008_merge_0002_student_srr_0007_alter_teacher_num_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='srr',
        ),
    ]
