# Generated by Django 4.0.4 on 2022-09-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_user_subjects_alter_subject_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterionA', models.IntegerField(default=0, null=True)),
                ('criterionB', models.IntegerField(default=0, null=True)),
                ('criterionC', models.IntegerField(default=0, null=True)),
                ('criterionD', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='score',
        ),
        migrations.AddField(
            model_name='subject',
            name='score',
            field=models.ManyToManyField(to='dashboard.grades'),
        ),
    ]
