# Generated by Django 4.0.3 on 2022-09-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_username_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Username',
        ),
    ]
