# Generated by Django 4.0.3 on 2022-09-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_grades_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='score',
        ),
        migrations.AddField(
            model_name='subject',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.grade'),
        ),
    ]
