# Generated by Django 4.0.3 on 2022-09-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_subject_score_subject_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.user'),
        ),
    ]
