# Generated by Django 4.0.3 on 2022-09-25 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_subject_score_remove_user_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.user'),
        ),
    ]
