# Generated by Django 4.0.3 on 2022-12-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_grade_subject_remove_subject_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
