# Generated by Django 4.0.3 on 2022-12-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subject',
            new_name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='srr',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
