# Generated by Django 4.0.3 on 2023-03-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_grade_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='avg',
            field=models.FloatField(default=0, null=True),
        ),
    ]
