# Generated by Django 4.0.3 on 2023-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_grade_srr_srr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srr',
            name='bestatl',
            field=models.CharField(choices=[('Interaction', 'Interaction'), ('Language', 'Language'), ('Collaboration', 'Collaboration'), ('Information Literacy', 'Information Literacy'), ('Media Literacy', 'Media Literacy'), ('Affective Skills', 'Affective Skills'), ('Organizational Skills', 'Organizational Skills'), ('Reflection', 'Reflection'), ('Critical Thinking', 'Critical Thinking'), ('Creative Thinking', 'Creative Thinking'), ('Transfer', 'Transfer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='srr',
            name='worstatl',
            field=models.CharField(choices=[('Interaction', 'Interaction'), ('Language', 'Language'), ('Collaboration', 'Collaboration'), ('Information Literacy', 'Information Literacy'), ('Media Literacy', 'Media Literacy'), ('Affective Skills', 'Affective Skills'), ('Organizational Skills', 'Organizational Skills'), ('Reflection', 'Reflection'), ('Critical Thinking', 'Critical Thinking'), ('Creative Thinking', 'Creative Thinking'), ('Transfer', 'Transfer')], max_length=50),
        ),
    ]
