# Generated by Django 4.1.2 on 2023-07-26 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_srr_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='srr',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
