# Generated by Django 4.0.3 on 2023-08-02 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_srr_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.profile'),
        ),
    ]
