# Generated by Django 4.0.3 on 2023-08-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_remove_grade_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subjectname', 'profile')},
        ),
    ]
